import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Sans_JP} from 'next/font/google'
import "./globals.css";
import Header from "./components/Header";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "./lib/next-auth/provider";


const NotoSansJP = Noto_Sans_JP({subsets:["latin"],weight:["400"]});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Book commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={NotoSansJP.className}
      >
        <NextAuthProvider>
        <Header></Header>
        {children}
        </NextAuthProvider>
      </body>
    </html>
  );

  // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
}
